name: Compiler CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  tests-ubuntu:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libreadline-dev ocl-icd-opencl-dev
      - name: List files and show Makefile
        run: |
          pwd
          ls -lR
          cat Makefile
      - name: Build cucpp
        run: |
          make re
      - name: Run Integration Tests
        run:
          make test

  tests-fedora-42:
    runs-on: fedora-42
    steps:
      - name: Install Dependencies
        run: |
          sudo dnf -y update
          sudo dnf -y install @development-tools readline-devel
      - name: Build cucpp
        run: |
          make re
      - name: Run Integration Tests
        run: |
          make test

